targets:
  odmx:
    build: .
    resolve_symlinks: true
    non_dockerfile_deps:
      - python-ssi-config
      - python-ssi-db
    args:
      PYLINT_VER: $PYLINT_VER
      PYTEST_VER: $PYTEST_VER

